pik-piam/magclass

DESCRIPTION, R/read.magpie.R
2 calcHistory read issues fixed
=> bugfixes in read.magpie

DESCRIPTION, R/getSets.R, man/calibrate_it.Rd, man/convergence.Rd, man/convert.report.Rd, man/copy.attributes.Rd, man/getMetadata.Rd, man/lin.convergence.Rd, man/new.magpie.Rd, man/read.lpjml_nc.Rd, man/read.magpie.Rd, man/time_interpolate.Rd, man/updateMetadata.Rd, man/write.magpie.Rd, man/write.magpie.ncdf.Rd, man/write.report.Rd, man/write.report2.Rd, man/write.reportProject.Rd
- bugfix in getSets<- fixing an error which appeared with duplicate setNames in different main dimensions
- Rd files updated from roxygen with a different stylage of the usage section
=> Bugfix in getSets<-

DESCRIPTION, R/magpie_expand_dim.R, tests/testthat/test-magpie_expand.R
Units containing brackets are now supported
=> bugfix in write.report2

DESCRIPTION, R/magpie_expand.R, man/magpie_expand.Rd, tests/testthat/test-magpie_expand.R
- switched default magpie_expand version to 2.1 (now with support for partial expansion --> fix for issue #47)
- cleaned corresponding tests
=> added support for partial expansion in magpie_expand

DESCRIPTION, R/getSets.R, man/getSets.Rd, tests/testthat/test-getSets.R
- getSets add now dimCode information to output and set manipulation can be adressed via dimCode
=> - added dimCode to getSets output

.zenodo.json, DESCRIPTION, R/write.report2.R, README.md
=> made sure the ... arguments are passed on to write.report2 

.buildlibrary, .zenodo.json, DESCRIPTION, R/magpie-class.R, README.md, tests/testthat/test-magpie.R
population_magpie[3] was not returning expected result
=> Bugfix in subsetting method

.buildlibrary, .zenodo.json, DESCRIPTION, R/as.magpie.R, README.md
Issue seems to be caused by data.table having problems with x[,i] syntax. x[[i]] syntax is now used instead
=> bugfix in datacol detection for data.frames

.buildlibrary, .github/workflows/test-buildlibrary.yaml, .zenodo.json, DESCRIPTION, R/read.report.R, README.md
This crap was bugging me for weeks.
=> fix aec6671 you missed a spot

.buildlibrary, .zenodo.json, DESCRIPTION, R/write.magpie.R, README.md, tests/testthat/test-as.data.frame.R
region names longer than 3 letters were sometimes incorrectly cut short to 3 letters
=> bugfix in write.magpie

.buildlibrary, .zenodo.json, DESCRIPTION, R/magpie-class.R, README.md, tests/testthat/test-ifelse.R, tests/testthat/test-magpie.R
similar bugfix as in previous PR fixing the issue that a different order of data and selector led to an incorrect selection of elements
=> fixed bug in magclass subsetting

.buildlibrary, .zenodo.json, DESCRIPTION, R/magpie-class.R, README.md, tests/testthat/test-magpie.R
strongly limited instances in which subset is expanded via magpie_expand
=> Bugfix in subsetting via magclass object

.buildlibrary, .zenodo.json, DESCRIPTION, R/read.magpie.R, R/write.magpie.R, README.md, tests/testthat/test-readwritemagpie.R
- re-added possibility to write multilayer nc files
- fixed a problem in which read.magpie was stopped by an error reading in nc files which contain variables which are not mapped to spatial dimensions
=> Bugfixes/improvements in read/write.magpie for NetCDF files

.buildlibrary, .zenodo.json, CRAN-RELEASE, DESCRIPTION, R/as.RasterBrick.R, R/ifelse.R, README.md, cran-comments.md
- fixing issue that multilayer raster objects lost their naming and were stored incorrectly
- (potentially) fixing exotic problem in which ifelse-tests failed on windows machines
=> Fix in magclass2raster conversion

.buildlibrary, .github/workflows/lucode2-check.yaml, .zenodo.json, DESCRIPTION, R/clean_magpie.R, R/getItems.R, README.md, man/clean_magpie.Rd, tests/testthat/test-getItems.R
fixing incorrect dimension assignment in cases in which a magclass object has improperly set set names
=> bugfix in getItems<-

.Rbuildignore, .buildlibrary, .github/workflows/lucode2-check.yaml, .pre-commit-config.yaml, .zenodo.json, DESCRIPTION, R/write.magpie.R, README.md, man/write.magpie.Rd
param x magclass or RasterBrick object. RasterBrick works only with file_types "nc", "asc", "grd" and "tif".
=> added option in write.magpie for working with RasterBrick objects

.Rbuildignore, .buildlibrary, .zenodo.json, DESCRIPTION, R/write.report.R, README.md, tests/testthat/test-readwritereport.R
Hi,
This adds support for variable names containing braces in every part of the variable name to writeReport.
Also adds a battery of tests for weird variable names.
Please review this thoroughly, it is my first "proper" pull request and my first time writing R code for production.
Cheers,
Mika
=> Support braces in variable names for writeReport

.buildlibrary, .pre-commit-config.yaml, .zenodo.json, DESCRIPTION, R/write.magpie.R, README.md, magclass.Rproj, man/write.magpie.Rd
change in write.magpie to make more flexible the variables name in the generated .nc maps
=> write.mapie flexible for time .nc variable naming

.buildlibrary, .zenodo.json, DESCRIPTION, R/write.magpie.R, README.md
Small bugfix on time dimension for .nc files in write.magpie
=> name of years in .nc bugfix

.buildlibrary, .github/workflows/lucode2-check.yaml, .pre-commit-config.yaml, .zenodo.json, DESCRIPTION, R/new.magpie.R, README.md, man/copy.attributes.Rd, man/getCells.Rd, man/getComment.Rd, man/getCoords.Rd, man/getItems.Rd, man/getNames.Rd, man/getRegionList.Rd, man/getRegions.Rd, man/getSets.Rd, man/getYears.Rd, man/mselect.Rd, man/ncells.Rd, man/new.magpie.Rd
=> mark unit argument in new.magpie as deprecated

.buildlibrary, .pre-commit-config.yaml, CITATION.cff, DESCRIPTION, Makefile, R/magpie-class.R, README.md, tests/testthat/test-magpie.R
Restructured argument list in "[" and "[<-" methods to make it compatible with current R-develop. In addition this fixes also #150
=> Restructured argument list in "[" and "[<-" methods

.buildlibrary, .github/workflows/check.yaml, .pre-commit-config.yaml, CITATION.cff, DESCRIPTION, R/mbind.R, README.md, tests/testthat/test-mbind.R
This check detects if the overall object size (sum of length of all objects) changes during `mbind` and throws an error if that happens.
=> added consistency check to mbind

.buildlibrary, CITATION.cff, DESCRIPTION, README.md
Crap.  I thought about doing further tests, to build a development version, then realised changes are limited to code that fails anyhow, and did not update the version afterwards.
There is a Github workflow somewhere to guard against merging development versions, no?
=> Correct Package Version
